## compute parameters in production cluster

# Linux Layer2 Bond
# bond not supported on container Ubuntu 
# trunk_bond:
#   id: 0
#   desc: "Linux Layer2 Bond Intf"
#   vlans:
#     - id: 101
#       addr_v4: "{{ v101_addr_v4 }}"
#       addr_v6: "{{ v101_addr_v6 }}"
#       routes_v4: "{{ v101_routes_v4 }}"
#       gw_v4: "{{ v101_gw_v4 }}"
#       routes_v6: "{{ v101_routes_v6 }}"
#       gw_v6: "{{ v101_gw_v6 }}"
#     - id: 201
#       addr_v4: "{{ v201_addr_v4 }}"
#       addr_v6: "{{ v201_addr_v6 }}"
#       routes_v4: "{{ v201_routes_v4 }}"
#       gw_v4: "{{ v201_gw_v4 }}"
#       routes_v6: "{{ v201_routes_v6 }}"
#       gw_v6: "{{ v201_gw_v6 }}"
#   bmem_indiv:
#     - "eth1"
#     - "eth2"

# Linux Layer2 Bond
# bond not supported on container Ubuntu 
trunk_port:
  bmem_indiv:
    - "eth1"
    - "eth2"  

v101_addr_v4: "{{ v101_netv4 | ansible.utils.ipaddr(seq-100) }}"
v101_addr_v6: "{{ v101_netv6 | ansible.utils.ipaddr('%0x' % seq-100) }}"
v101_gw_v4: "{{ v101_netv4 | ansible.utils.ipaddr(1) | ansible.utils.ipaddr('address') }}"
v101_gw_v6: "{{ v101_netv6 | ansible.utils.ipaddr(1) | ansible.utils.ipaddr('address') }}"
v101_routes_v4:
   -
      dst: "{{ compute_lpbk0_netv4 }}"
   -
      dst: "{{ v201_netv4 }}"
   -
      dst: "{{ v301_netv4 }}"
   -
      dst: "{{ v104_netv4 }}"
   -
      dst: "{{ v204_netv4 }}"
v101_routes_v6:
   -
      dst: "{{ compute_lpbk0_netv6 }}"
   -
      dst: "{{ v201_netv6 }}"
   -
      dst: "{{ v301_netv6 }}"
   -
      dst: "{{ v104_netv6 }}"
   -
      dst: "{{ v204_netv6 }}"

v104_addr_v4: "{{ v104_netv4 | ansible.utils.ipaddr(seq-100) }}"
v104_addr_v6: "{{ v104_netv6 | ansible.utils.ipaddr(seq-100) }}"
v104_gw_v4: "{{ v104_netv4 | ansible.utils.ipaddr(1) | ansible.utils.ipaddr('address') }}"
v104_gw_v6: "{{ v104_netv6 | ansible.utils.ipaddr(1) | ansible.utils.ipaddr('address') }}"
v104_routes_v4:
   -
      dst: "{{ compute_lpbk0_netv4 }}"
   -
      dst: "{{ v101_netv4 }}"
   -
      dst: "{{ v201_netv4 }}"
   -
      dst: "{{ v301_netv4 }}"
   -
      dst: "{{ v204_netv4 }}"
   -
      dst: "{{ v304_netv4 }}"
v104_routes_v6:
   -
      dst: "{{ compute_lpbk0_netv6 }}"
   -
      dst: "{{ v101_netv6 }}"
   -
      dst: "{{ v201_netv6 }}"
   -
      dst: "{{ v301_netv6 }}"
   -
      dst: "{{ v204_netv6 }}"
   -
      dst: "{{ v304_netv6 }}"

v201_addr_v4: "{{ v201_netv4 | ansible.utils.ipaddr(seq-100) }}"
v201_addr_v6: "{{ v201_netv6 | ansible.utils.ipaddr(seq-100) }}"
v201_gw_v4: "{{ v201_netv4 | ansible.utils.ipaddr(1) | ansible.utils.ipaddr('address') }}"
v201_gw_v6: "{{ v201_netv6 | ansible.utils.ipaddr(1) | ansible.utils.ipaddr('address') }}"
v201_routes_v4:
   -
      dst: "{{ compute_lpbk0_netv4 }}"
   -
      dst: "{{ v101_netv4 }}"
   -
      dst: "{{ v301_netv4 }}"
   -
      dst: "{{ v104_netv4 }}"
   -
      dst: "{{ v204_netv4 }}"
v201_routes_v6:
   -
      dst: "{{ compute_lpbk0_netv6 }}"
   -
      dst: "{{ v101_netv6 }}"
   -
      dst: "{{ v301_netv6 }}"
   -
      dst: "{{ v104_netv6 }}"
   -
      dst: "{{ v204_netv6 }}"

v204_addr_v4: "{{ v204_netv4 | ansible.utils.ipaddr(seq-100) }}"
v204_addr_v6: "{{ v204_netv6 | ansible.utils.ipaddr(seq-100) }}"
v204_gw_v4: "{{ v204_netv4 | ansible.utils.ipaddr(1) | ansible.utils.ipaddr('address') }}"
v204_gw_v6: "{{ v204_netv6 | ansible.utils.ipaddr(1) | ansible.utils.ipaddr('address') }}"
v204_routes_v4:
   -
      dst: "{{ compute_lpbk0_netv4 }}"
   -
      dst: "{{ v204_netv4 }}"
   -
      dst: "{{ v201_netv4 }}"
   -
      dst: "{{ v104_netv4 }}"
v204_routes_v6:
   -
      dst: "{{ compute_lpbk0_netv6 }}"
   -
      dst: "{{ v204_netv6 }}"
   -
      dst: "{{ v201_netv6 }}"
   -
      dst: "{{ v104_netv6 }}"

v301_addr_v4: "{{ v301_netv4 | ansible.utils.ipaddr(seq-100) }}"
v301_addr_v6: "{{ v301_netv6 | ansible.utils.ipaddr(seq-100) }}"
v301_gw_v4: "{{ v301_netv4 | ansible.utils.ipaddr(1) | ansible.utils.ipaddr('address') }}"
v301_gw_v6: "{{ v301_netv6 | ansible.utils.ipaddr(1) | ansible.utils.ipaddr('address') }}"
v301_routes_v4:
   -
      dst: "{{ compute_lpbk0_netv4 }}"
   -
      dst: "{{ v301_netv4 }}"
   -
      dst: "{{ v201_netv4 }}"
   -
      dst: "{{ v104_netv4 }}"
   -
      dst: "{{ v204_netv4 }}"
v301_routes_v6:
   -
      dst: "{{ compute_lpbk0_netv6 }}"
   -
      dst: "{{ v301_netv6 }}"
   -
      dst: "{{ v201_netv6 }}"
   -
      dst: "{{ v104_netv6 }}"
   -
      dst: "{{ v204_netv6 }}"

v304_addr_v4: "{{ v304_netv4 | ansible.utils.ipaddr(seq-100) }}"
v304_addr_v6: "{{ v304_netv6 | ansible.utils.ipaddr(seq-100) }}"
v304_gw_v4: "{{ v304_netv4 | ansible.utils.ipaddr(1) | ansible.utils.ipaddr('address') }}"
v304_gw_v6: "{{ v304_netv6 | ansible.utils.ipaddr(1) | ansible.utils.ipaddr('address') }}"
v304_routes_v4:
   -
      dst: "{{ compute_lpbk0_netv4 }}"
   -
      dst: "{{ v304_netv4 }}"
   -
      dst: "{{ v201_netv4 }}"
   -
      dst: "{{ v104_netv4 }}"
   -
      dst: "{{ v204_netv4 }}"
v304_routes_v6:
   -
      dst: "{{ compute_lpbk0_netv6 }}"
   -
      dst: "{{ v304_netv6 }}"
   -
      dst: "{{ v201_netv6 }}"
   -
      dst: "{{ v104_netv6 }}"
   -
      dst: "{{ v204_netv6 }}"
