---
ansible_ssh_user: admin
ansible_ssh_pass: "{{vault_os10_password}}"
ansible_connection: network_cli
ansible_network_os: dellos10
ansible_become: yes
ansible_become_method: sudo
ansible_become_pass: "{{ vault_os10_password }}"

dellos_image_upgrade:
    operation_type: install
    software_image_url: "http://172.100.100.81/PKGS_OS10-Enterprise-10.5.2.8.380stretch-installer-x86_64.bin"
    software_version: 10.5.2.8
    # software_image_url: "http://172.100.100.81/PKGS_OS10-Enterprise-10.5.2.7.374stretch-installer-x86_64.bin"
    # software_version: 10.5.2.7
    number_of_retries: 50

dellos_system: "{{ all_system }}"

policy:
    comm_list:
        -
            name: "pe_edge"
            permit:
                - "{{ rack_tor_asn }}:10101"
                - "{{ rack_tor_asn }}:10201"
                - "{{ rack_tor_asn }}:10301"
            deny:
        -
            name: "EVPN_PE"
            permit:
                - "65000:0000"
                - "65100:9001"
                - "65100:9002"
            deny:
    as_path:
        -
            name: "traverse_cluster"
            path:
                - "_{{ spine_asn }}_"
                - "_{{ rack01_asn }}_"
                - "_{{ rack02_asn }}_"
                - "_{{ rack03_asn }}_"
                - "_{{ rack04_asn }}_"
        -
            name: "local_orig"
            path:
                - "^$"
    prefix_list:
        -
            name: "V4_CONNECTED"
            afi: "ipv4"
            step: 10
            prefix:
                -
                    action: "permit"
                    range: "{{ lpbk0_netv4 }} le 32"
                -
                    action: "permit"
                    range: "{{ lpbk1_netv4 }} le 32"
                -
                    action: "permit"
                    range: "10.10.0.0/16 le 32"
                -
                    action: "permit"
                    range: "{{ edge_netv4 }} le 32"
                -
                    action: "permit"
                    range: "{{ v101_netv4 }} le 32"
                -
                    action: "permit"
                    range: "{{ v104_netv4 }} le 32"
                -
                    action: "permit"
                    range: "{{ v121_netv4 }} le 32"
                -
                    action: "permit"
                    range: "{{ v124_netv4 }} le 32"
                -
                    action: "permit"
                    range: "{{ v141_netv4 }} le 32"
                -
                    action: "permit"
                    range: "{{ v142_netv4 }} le 32"
                -
                    action: "permit"
                    range: "{{ v201_netv4 }} le 32"
                -
                    action: "permit"
                    range: "{{ v204_netv4 }} le 32"
                -
                    action: "permit"
                    range: "{{ v301_netv4 }} le 32"
                -
                    action: "permit"
                    range: "{{ v304_netv4 }} le 32"
        -
            name: "V6_CONNECTED"
            afi: "ipv6"
            step: 10
            prefix:
                -
                    action: "permit"
                    range: "{{ lpbk0_netv6 }} le 128"
                -
                    action: "permit"
                    range: "{{ lpbk1_netv6 }} le 128"
                -
                    action: "permit"
                    range: "{{ edge_netv6 }} le 128"
                -
                    action: "permit"
                    range: "{{ v101_netv6 }} le 128"
                -
                    action: "permit"
                    range: "{{ v104_netv6 }} le 128"
                -
                    action: "permit"
                    range: "{{ v121_netv6 }} le 128"
                -
                    action: "permit"
                    range: "{{ v124_netv6 }} le 128"
                -
                    action: "permit"
                    range: "{{ v141_netv6 }} le 128"
                -
                    action: "permit"
                    range: "{{ v142_netv6 }} le 128"
                -
                    action: "permit"
                    range: "{{ v201_netv6 }} le 128"
                -
                    action: "permit"
                    range: "{{ v204_netv6 }} le 128"
                -
                    action: "permit"
                    range: "{{ v301_netv6 }} le 128"
                -
                    action: "permit"
                    range: "{{ v304_netv6 }} le 128"
        -
            name: "V4-NH"
            afi: "ipv4"
            step: 5
            prefix:
                -
                    action: "permit"
                    range: "192.16.1.0/24 le 32"
                -
                    action: "permit"
                    range: "24.127.1.0/24 le 32"
        -
            name: "FABRIC_PTP_V4"
            afi: "ipv4"
            step: 5
            prefix:
                -
                    action: "permit"
                    range: "{{ fabric_ptp_netv4 }} le 32"
        -
            name: "FABRIC_PTP_V6"
            afi: "ipv6"
            step: 5
            prefix:
                -
                    action: "permit"
                    range: "{{ fabric_ptp_netv6 }} le 128"

    route_map:
        -
            name: "LOCAL_CONNECTED_V4"
            step: 10
            match:
                -
                    type: "ip address prefix-list"
                    object: "V4_CONNECTED"
                    action:
                -
                    type: "community"
                    object: "EVPN_PE"
                    action:
        -
            name: "LOCAL_CONNECTED_V6"
            step: 10
            match:
                -
                    type: "ipv6 address prefix-list"
                    object: "V6_CONNECTED"
                    action:
        -
            name: "drain_ingress_tfk"
            step: 10
            match:
                -
                    type:
                    object: 
                    action:
                        type: "as-path prepend"
                        object: "{{ rack_tor_asn }} {{ rack_tor_asn }} {{ rack_tor_asn }} "
        -
            name: "drain_egress_tfk"
            step: 10
            match:
                -
                    type: 
                    object: 
                    action:
                        type: "local-preference"
                        object: "90"
        -
            name: "EVPN_EXPORT"
            step: 10
            match:
                -
                    type: "as-path"
                    object: "local_orig"
                    action:
        -
            name: "SET_NH_V6"
            step: 10
            match:
                -
                    type: 
                    object:
                    action:
                        type: "ipv6 next-hop"
                        object: "2001:2001::1"
