---
ansible_ssh_user: lab
ansible_ssh_pass: "{{vault_lab_password}}"
ansible_sudo_pass: "{{vault_lab_password}}"
ansible_linux_os: photonos
ansible_os_family: photonos
vendor: "VMWare ESXi"

ansible_python_interpreter: /usr/bin/python3

photon_yum_repo: https://vmware.bintray.com/photon_pre_release_1.0_x86_64
photon_yum_repo_enabled: yes

photon_packages:
#   - python2
#   - python2-devel
#   - python2-libs
#   - git
#   - gzip
  # - less
#   - python-setuptools
#   - tar
  - iputils
  - traceroute
  - tcpdump
  - lldpad
  - net-tools
  - sudo
  - iperf
  - iperf-doc
  - netcat
  - iproute2
  - gawk

ports:
   "eth0":
      desc: "Mgmt Port"
      addr_v4: "{{ ansible_host }}"
      routes_v4: "default"
      gw_v4: "{{ oob_netv4_gw }}"
      dns: "{{ services.dns }}"

   "eth1":
      desc: "{{ eth1_desc }}"
      addr_v4: "{{ v101_addr_v4 }}"
      addr_v6: "{{ v101_addr_v6 }}"
      routes_v4: "{{ v101_routes_v4 }}"
      gw_v4: "{{ v101_gw_v4 }}"
      routes_v6: "{{ v101_routes_v6 }}"
      gw_v6: "{{ v101_gw_v6 }}"

   "lo":
      desc: "Loopback"
      addr_v4: "{{ compute_lpbk0_netv4 | ansible.utils.ipaddr(seq-100) | ansible.utils.ipaddr('address') }}/32"
      addr_v6: "{{ compute_lpbk0_netv6 | ansible.utils.ipaddr(seq-100) | ansible.utils.ipaddr('address') }}/128"

connectivity_test_destinations:
  - { ip: 10.100.2.12, port: 22 }
  - { ip: 10.100.1.13, port: 5000 }
  - { ip: 10.100.2.14, port: 53, protocol: udp }