---
edge_links:
   -
    name: "1/1"
    state: "present"
    desc: "EDGE to ISP GW"
    admin_state: "up"
    net_v4: "{{ edge_netv4|ansible.utils.ipsubnet(edge_netmaskv4, edge_seq) }}"
    net_v6: "{{ edge_netv6|ansible.utils.ipsubnet(edge_netmaskv6, edge_seq) }}"
    ## Edge Addr higher(2), ISP lower(1)
    addr_v4: "{{ edge_netv4|ansible.utils.ipsubnet(edge_netmaskv4, edge_seq)|ansible.utils.ipaddr(2) }}"
    addr_v6: "{{ edge_netv6|ansible.utils.ipsubnet(edge_netmaskv6, edge_seq)|ansible.utils.ipaddr(2) }}"
    vrf: PNAP-EDGE
#    -
#     name: "2"
#     state: "present"    
#     desc: "ISP GW To EDGE"
#     admin_state: "up"
#     net_v4: "{{ edge_netv4|ansible.utils.ipsubnet(edge_netmaskv4, links_seq[1]) }}"
#     net_v6: "{{ edge_netv6|ansible.utils.ipsubnet(edge_netmaskv6, links_seq[1]) }}"
#     vrf:

# edge_vlans:
#    -
#     id: "1991"
#     port: "27"
#     state: "present"    
#     desc: "ISP GW To EDGE"
#     admin_state: "up"
#     net_v4: "{{ edge_netv4|ansible.utils.ipsubnet(edge_netmaskv4, links_seq[0]) }}"
#     net_v6: "{{ edge_netv6|ansible.utils.ipsubnet(edge_netmaskv6, links_seq[0]) }}"
#     vrf:
#    -
#     id: "1992"
#     port: "28"
#     state: "present"    
#     desc: "ISP GW To EDGE"
#     admin_state: "up"
#     net_v4: "{{ edge_netv4|ansible.utils.ipsubnet(edge_netmaskv4, links_seq[0]) }}"
#     net_v6: "{{ edge_netv6|ansible.utils.ipsubnet(edge_netmaskv6, links_seq[0]) }}"
#     vrf:
test_links:
   -
    name: 
    state: "present"    
    desc: "To IXIA"
    admin_state: "up"
    net_v4: "{{ test_netv4|ansible.utils.ipsubnet(test_netmaskv4, seq-101 ) }}"
    net_v6: "{{ test_netv6|ansible.utils.ipsubnet(test_netmaskv6, seq-101 ) }}"
## Edge Addr higher(2), ISP lower(1)
    addr_v4: "{{ test_netv4|ansible.utils.ipsubnet(edge_netmaskv4, seq-101)|ansible.utils.ipaddr(1) }}"
    addr_v6: "{{ test_netv6|ansible.utils.ipsubnet(edge_netmaskv6, seq-101)|ansible.utils.ipaddr(1) }}"
    vrf:

edge_bgp:
  local_as: "{{ edge_asn }}"
  peer_group:
  -
    name: "ISP-PEER-GROUP_v4"
    desc: "GENERIC-ISP-PG"
    remote_as:
    admin_state: "up"
    afi:
    - "ipv4"
    attributes:
      - "remove-private-as"
      - "route-map ISP-GENERIC-IN in"
      - "route-map ISP-GENERIC-OUT out"
      - "send-community"
      - "ebgp-multihop 2"
      - "maximum-routes 0"
  -
    name: "ISP-PEER-GROUP_v6"
    desc: "GENERIC-ISP-PG"
    remote_as:
    admin_state: "up"
    afi:
    - "ipv6"
    attributes:
      - "remove-private-as"
      - "route-map ISP-GENERIC-IN in"
      - "route-map ISP-GENERIC-OUT out"
      - "send-community"
      - "ebgp-multihop 2"
      - "maximum-routes 0"
  -
    name: "tester_v4"
    desc: "IXIA PG V4"
    remote_as: "1234"
    admin_state: "up"
    afi:
    - "ipv4"
    attributes:
      - "send-community"
      - "ebgp-multihop 5"
      - "maximum-routes 0"
  -
    name: "tester_v6"
    desc: "IXIA PG V6"
    remote_as: "1234"
    admin_state: "up"
    afi:
    - "ipv6"
    attributes:
      - "send-community"
      - "ebgp-multihop 5"
      - "maximum-routes 0"
  peers:
    - 
      addr: "{{ edge_links[0].net_v4 | ansible.utils.(1) | ansible.utils.ipaddr('address') }}"
      desc: "DC Fabric Edge Peer V4"
      remote_as: "{{ remote_isp_asn }}"
      peer_group: "ISP-PEER-GROUP_v4"
    - 
      addr: "{{ edge_links[0].net_v6 | ansible.utils.ipaddr(1) | ansible.utils.ipaddr('address') }}"
      desc: "DC Fabric Edge Peer V6"
      remote_as: "{{ remote_isp_asn }}"
      peer_group: "ISP-PEER-GROUP_v6"
    - 
      addr: "{{ test_links[0].net_v4 | ansible.utils.ipaddr(2) | ansible.utils.ipaddr('address') }}"
      desc: "Tester Peer V4"
      remote_as:
      peer_group: "tester_v4"
    - 
      addr: "{{ test_links[0].net_v6 | ansible.utils.ipaddr(2) | ansible.utils.ipaddr('address') }}"
      desc: "Tester Peer V6"
      remote_as:
      peer_group: "tester_v6"
  afi: 
  #   ipv4:
  #   -
  #       r_map: "LOCAL_CONNECTED_V4"
  #       proto: connected
  #   ipv6:
  #   -
  #       r_map: "LOCAL-LOOPBACK-V6"
  #       proto: connected
  # flowspec: 
  #   ipv4: "disable"
  #   ipv6: "disable"

