# Location:
rack_no: 2

vxlan_rvtep:
    - 10.10.0.1
    - 10.10.0.3

vxlan_id_prx: "10"
vxlans:
#   id_prx: "10"
#    - 
#         desc: << descirption of Vlan func, optional>>
#         vlan: << vlan id, mandate>>
#         netv4: << Preassigned network block, optional >>
#         netv6: << Preassigned network block, optional >>
#         vrf: << VRF name the vlan belong to, mandate >>
#         state: << state value, [present|absence], mandate >>
    - 
        desc: "overlay_vlan"
        vlan: "101"
        netv4: "{{ v101_netv4 }}"
        netv6: "{{ v101_netv6 }}"
        vrf: "BMS-subnet"
        helper_addrv4:
            - 11.11.11.11
            - 12.12.12.12
        state: "present"
    - 
        desc: "overlay_vlan"
        vlan: "201"
        netv4: "{{ v201_netv4 }}"
        netv6: "{{ v201_netv6 }}"
        vrf: "BMS-subnet"
        helper_addrv4:
            - 11.11.11.11
            - 12.12.12.12
        state: "present"
    - 
        desc: "overlay_vlan"
        vlan: "202"
        netv4: "{{ v202_netv4 }}"
        netv6: "{{ v202_netv6 }}"
        vrf: "BMS-subnet"
        helper_addrv4:
            - 11.11.11.11
            - 12.12.12.12
        state: "present"
    - 
        desc: "overlay_vlan"
        vlan: "141"
        # netv4: "{{ v141_netv4 }}"
        # netv6: "{{ v141_netv6 }}"
        vrf: "BMS-subnet"
        # helper_addrv4:
        #     - 11.11.11.11
        #     - 12.12.12.12
        state: "present"
    - 
        desc: "overlay_vlan"
        vlan: "142"
        # netv4: "{{ v142_netv4 }}"
        # netv6: "{{ v142_netv6 }}"
        vrf: "BMS-subnet"
        # helper_addrv4:
        #     - 11.11.11.11
        #     - 12.12.12.12
        state: "present"
    - 
        desc: "overlay_vlan"
        vlan: "143"
        # netv4: "{{ v143_netv4 }}"
        # netv6: "{{ v143_netv6 }}"
        vrf: "BMS-subnet"
        helper_addrv4:
            - 11.11.11.11
            - 12.12.12.12
        state: "present"
