# Location:
rack_no: 1

vlt_primary_priority: 1
vlt_backup_destination: "{{ hostvars['sw1001b-x']['ansible_host'] }}"

vxlan_rvtep:
    - 10.10.0.2
    - 10.10.0.3

vxlan_id_prx: "10"
vxlans:
#   id_prx: "10"
#    - 
#         desc: << descirption of Vlan func, optional>>
#         vlan: << vlan id, mandate>>
#         netv4: << Preassigned network block, optional >>
#         netv6: << Preassigned network block, optional >>
#         vrf: << VRF name the vlan belong to, mandate >>
#         state: << state value, [present|absence], mandate >>
    - 
        desc: "overlay_vlan"
        vlan: "101"
        netv4: "{{ v101_netv4 }}"
        netv6: "{{ v101_netv6 }}"
        vrf: "SDDC"
        # helper_addrv4:
        #     - 11.11.11.11
        #     - 12.12.12.12
        state: "present"
    - 
        desc: "overlay_vlan"
        vlan: "102"
        # netv4: "{{ v102_netv4 }}"
        # netv6: "{{ v102_netv6 }}"
        vrf: "SDDC"
        # helper_addrv4:
        #     - 11.11.11.11
        #     - 12.12.12.12
        state: "present"
    - 
        desc: "overlay_vlan"
        vlan: "103"
        netv4: "{{ v103_netv4 }}"
        netv6: "{{ v103_netv6 }}"
        vrf: "SDDC"
        # helper_addrv4:
        #     - 11.11.11.11
        #     - 12.12.12.12
        state: "absence"
    - 
        desc: "overlay_vlan"
        vlan: "141"
        # netv4: "{{ v141_netv4 }}"
        # netv6: "{{ v141_netv6 }}"
        vrf: "SDDC"
        # helper_addrv4:
        #     - 11.11.11.11
        #     - 12.12.12.12
        state: "absence"
    - 
        desc: "overlay_vlan"
        vlan: "142"
        # netv4: "{{ v142_netv4 }}"
        # netv6: "{{ v142_netv6 }}"
        vrf: "SDDC"
        # helper_addrv4:
        #     - 11.11.11.11
        #     - 12.12.12.12
        state: "absence"
    - 
        desc: "overlay_vlan"
        vlan: "143"
        # netv4: "{{ v143_netv4 }}"
        # netv6: "{{ v143_netv6 }}"
        vrf: "SDDC"
        # helper_addrv4:
        #     - 11.11.11.11
        #     - 12.12.12.12
        state: "absence"
