---

## link seqeunce calculation
## link count per switch
link_ct: 1
offset: "{{ hostvars['dc-gw01'].seq }}"
links_seq:
    - "{{ (seq-offset|int)*link_ct + 0 }}"
    # - "{{ (seq-offset|int)*link_ct + 1 }}"

edge_links:
   -
    name: "1/1"
    state: "present"    
    desc: "ISP GW To EDGE"
    admin_state: "up"
    net_v4: "{{ edge_netv4|ansible.utils.ipsubnet(edge_netmaskv4, links_seq[0]) }}"
    net_v6: "{{ edge_netv6|ansible.utils.ipsubnet(edge_netmaskv6, links_seq[0]) }}"
    vrf:
#    -
#     name: "1/2"
#     state: "present"    
#     desc: "ISP GW To EDGE"
#     admin_state: "up"
#     net_v4: "{{ edge_netv4|ansible.utils.ipsubnet(edge_netmaskv4, links_seq[1]) }}"
#     net_v6: "{{ edge_netv6|ansible.utils.ipsubnet(edge_netmaskv6, links_seq[1]) }}"
#     vrf:

# edge_vlans:
#    -
#     id: "1991"
#     port: "27"
#     state: "present"    
#     desc: "ISP GW To EDGE"
#     admin_state: "up"
#     net_v4: "{{ edge_netv4|ansible.utils.ipsubnet(edge_netmaskv4, links_seq[0]) }}"
#     net_v6: "{{ edge_netv6|ansible.utils.ipsubnet(edge_netmaskv6, links_seq[0]) }}"
#     vrf:
#    -
#     id: "1992"
#     port: "28"
#     state: "present"    
#     desc: "ISP GW To EDGE"
#     admin_state: "up"
#     net_v4: "{{ edge_netv4|ansible.utils.ipsubnet(edge_netmaskv4, links_seq[0]) }}"
#     net_v6: "{{ edge_netv6|ansible.utils.ipsubnet(edge_netmaskv6, links_seq[0]) }}"
#     vrf:

test_links:
   -
    name: "31/1"
    state: "present"    
    desc: "To IXIA"
    admin_state: "up"
    net_v4: "{{ test_netv4|ansible.utils.ipsubnet(test_netmaskv4, links_seq[0]) }}"
    net_v6: "{{ test_netv6|ansible.utils.ipsubnet(test_netmaskv6, links_seq[0]) }}"
    vrf:

bgp:
  local_as: "{{ local_asn }}"
  peer-group:
    ipv4:
      - 
        name: "fabric_edge_v4"
        desc: "PEER GROUP to EDGE"
        remote_as: "{{ edge_asn }}"
        attributes:
          - "advertisement-interval 5"
          - "capability extended-nexthop"
          - "time 3 9"
          - "bfd"
          - "allowas-in"
          - "send-community standard extended"
      - 
        name: "tester_v4"
        remote_as: "{{ tester_asn }}"
        attributes:
          - "time 3 9"
          - "bfd"
          - "allowas-in"
          - "send-community standard extended"
    ipv6:
      - 
        name: "fabric_edge_v6"
        remote_as: "{{ edge_asn }}"
        attributes:
          - "time 3 9"
          - "bfd"
          - "allowas-in"
          - "send-community standard extended"
      - 
        name: "tester_v6"
        remote_as: "{{ tester_asn }}"
        attributes:
          - "time 3 9"
          - "bfd"
          - "allowas-in"
          - "send-community standard extended"
  peers:
    - 
      addr: "{{ edge_links[0].net_v4 | ansible.utils.ipaddr(2) | ansible.utils.ipaddr('address') }}"
      desc: "DC Fabric Edge Peer V4"
      remote_as:
      peer_group: "fabric_edge_v4"
    - 
      addr: "{{ edge_links[0].net_v6 | ansible.utils.ipaddr(2) | ansible.utils.ipaddr('address') }}"
      desc: "DC Fabric Edge Peer V6"
      remote_as:
      peer_group: "fabric_edge_v6"
    - 
      addr: "{{ test_links[0].net_v4 | ansible.utils.ipaddr(2) | ansible.utils.ipaddr('address') }}"
      desc: "Tester Peer V4"
      remote_as:
      peer_group: "tester_v4"
    - 
      addr: "{{ test_links[0].net_v6 | ansible.utils.ipaddr(2) | ansible.utils.ipaddr('address') }}"
      desc: "Tester Peer V6"
      remote_as:
      peer_group: "tester_v6"
  afi: 
    ipv4:
    -
        r_map: "LOCAL_CONNECTED_V4"
        proto: connected
    ipv6:
    -
        r_map: "LOCAL_CONNECTED_V6"
        proto: connected
  flowspec: 
    ipv4: "disable"
    ipv6: "disable"

