# Location:
rack_no: 1

vlt_primary_priority: 1
vlt_backup_destination: "{{ hostvars['sw1001b-x']['ansible_host'] }}"

vxlan_rvtep:
    - 10.10.0.2
    - 10.10.0.3

vxlans:
#    - 
#         desc: << descirption of Vlan func, optional>>
#         vlan: << vlan id, mandate>>
#         id: << vxlan id vlan mapped, mandate >>
#         netv4: << Preassigned network block, optional >>
#         netv6: << Preassigned network block, optional >>
#         vrf: << VRF name the vlan belong to, mandate >>
#         state: << state value, [present|absence], mandate >>
    - 
        desc: "vMgmt"
        vlan: "101"
        id: "10101"
        netv4: "{{ v101_netv4 }}"
        netv6: "{{ v101_netv6 }}"
        vrf: "RED"
        helper_addrv4:
            - 11.11.11.11
            - 12.12.12.12
        state: "present"
    - 
        desc: "vSAN"
        vlan: "201"
        id: "10201"
        # netv4: "{{ v201_netv4 }}"
        # netv6: "{{ v201_netv6 }}"
        vrf: "RED"
        helper_addrv4:
            - 11.11.11.11
            - 12.12.12.12
        state: "present"
    - 
        desc: "vTEP"
        vlan: "301"
        id: "10301"
        netv4: "{{ v301_netv4 }}"
        netv6: "{{ v301_netv6 }}"
        vrf: "RED"
        helper_addrv4:
            - 11.11.11.11
            - 12.12.12.12
        state: "absence"
    - 
        desc: "Extra_Vlan01"
        vlan: "401"
        id: "10401"
        # netv4: "{{ v401_netv4 }}"
        # netv6: "{{ v401_netv6 }}"
        vrf: "RED"
        helper_addrv4:
            - 11.11.11.11
            - 12.12.12.12
        state: "absence"
    - 
        desc: "Extra_Vlan2"
        vlan: "402"
        id: "10402"
        # netv4: "{{ v402_netv4 }}"
        # netv6: "{{ v402_netv6 }}"
        vrf: "RED"
        helper_addrv4:
            - 11.11.11.11
            - 12.12.12.12
        state: "absence"
    - 
        desc: "Extra_Vlan03"
        vlan: "403"
        id: "10403"
        # netv4: "{{ v403_netv4 }}"
        # netv6: "{{ v403_netv6 }}"
        vrf: "RED"
        helper_addrv4:
            - 11.11.11.11
            - 12.12.12.12
        state: "absence"

