edge_link_ct: 2
edge_offset: "{{ hostvars['bleaf01'].seq }}"
edge_links_seq:
    - "{{ edge_link_ct*(seq-edge_offset|int) }}"
    - "{{ edge_link_ct*(seq-edge_offset|int)+1 }}"

# edge_links:
#    -
#     port: "1"
#     desc: "Gateway uplink_To_CE01"
#     netv4: "{{ edge_netv4|ansible.utils.ipsubnet(edge_netmaskv4, edge_links_seq[0]) }}"
#     netv6: "{{ edge_netv6|ansible.utils.ipsubnet(edge_netmaskv6, edge_links_seq[0]) }}"
#     vrf: RED
#    -
#     port: "2"
#     desc: "Gateway uplink_To_CE02"
#     netv4: "{{ edge_netv4|ansible.utils.ipsubnet(edge_netmaskv4, edge_links_seq[1]) }}"
#     netv6: "{{ edge_netv6|ansible.utils.ipsubnet(edge_netmaskv6, edge_links_seq[1]) }}"
#     vrf: RED

# edge_vlans:
    # - 
    #     desc: "To CE01"
    #     id: "1991"
    #     netv4: "{{ edge_netv4|ansible.utils.ipsubnet(edge_netmaskv4, edge_links_seq[0]) }}"
    #     netv6: "{{ edge_netv6|ansible.utils.ipsubnet(edge_netmaskv6, edge_links_seq[0]) }}"
    #     port: 27
    #     vrf: RED
    # - 
    #     desc: "To CE02"
    #     id: "1992"
    #     netv4: "{{ edge_netv4|ansible.utils.ipsubnet(edge_netmaskv4, edge_links_seq[1]) }}"
    #     netv6: "{{ edge_netv6|ansible.utils.ipsubnet(edge_netmaskv6, edge_links_seq[1]) }}"
    #     port: 28
    #     vrf: RED

evpn:
    arp_suppression:
        pfx_list: "ARP_NO_PROXY"
    vrf:
    - 
        name: "DEFAULT"
        desc: "GLOBAL INSTANCE"
        rd_pfx: "{{ lpbk1.addr_v4 }}"
        rt_pfx:
        l3_vni: 
          id: "0"
        rleak_rules:
            rmap_out: "BGP-VRF-LEAK-OUT-DEFAULT"
            rmap_in:
            rt_import: "{{ bgp.local_as }}:999"
            rt_export: "{{ bgp.local_as }}:999"
    - 
        name: "RED"
        desc: "RED_VRF"
        rd_pfx: "{{ lpbk1.addr_v4 }}"
        rt_pfx: "1001"
        l3_vni: 
          id: "9001"
          vlan: "901"
        interfaces:
        - 
            name: "loopback901"
            desc: "Loopback Interface"
            addr_v4: "10.10.201.{{ seq }}/32"
            addr_v6: "2001:ffff:ffff::{{ '%0x' % seq }}/128"
        -
            name: "eth1"
            desc: "Gateway uplink_To_GW01"
            addr_v4: "{{ edge_netv4|ansible.utils.ipsubnet(edge_netmaskv4, edge_links_seq[0])|ansible.utils.ipaddr(1) }}"
            addr_v6: "{{ edge_netv6|ansible.utils.ipsubnet(edge_netmaskv6, edge_links_seq[0])|ansible.utils.ipaddr(1) }}"
        -
            name: "eth2"
            desc: "Gateway uplink_To_GW02"
            addr_v4: "{{ edge_netv4|ansible.utils.ipsubnet(edge_netmaskv4, edge_links_seq[1])|ansible.utils.ipaddr(1) }}"
            addr_v6: "{{ edge_netv6|ansible.utils.ipsubnet(edge_netmaskv6, edge_links_seq[1])|ansible.utils.ipaddr(1) }}"
        type5:
        - 
            afi: ipv4
            proto: connected
            r_map: 
        - 
            afi: ipv4
            proto: static
            r_map: 
        proto:
            bgp:
                gw_peer_v4:
                    - 
                        addr: "{{ edge_netv4|ansible.utils.ipsubnet(edge_netmaskv4, edge_links_seq[0]) | ansible.utils.ipaddr(-2) | ansible.utils.ipaddr('address') }}"
                        asn: "{{ 65000+hostvars['dc-gw01'].seq }}"
                    - 
                        addr: "{{ edge_netv4|ansible.utils.ipsubnet(edge_netmaskv4, edge_links_seq[1]) | ansible.utils.ipaddr(-2) | ansible.utils.ipaddr('address') }}"
                        asn: "{{ 65000+hostvars['dc-gw02'].seq }}"
                gw_peer_v6:
                    - 
                        addr: "{{ edge_netv6|ansible.utils.ipsubnet(edge_netmaskv6, edge_links_seq[0]) | ansible.utils.ipaddr(-2) | ansible.utils.ipaddr('address') }}"
                        asn: "{{ 65000+hostvars['dc-gw01'].seq }}"
                    - 
                        addr: "{{ edge_netv6|ansible.utils.ipsubnet(edge_netmaskv6, edge_links_seq[1]) | ansible.utils.ipaddr(-2) | ansible.utils.ipaddr('address') }}"
                        asn: "{{ 65000+hostvars['dc-gw02'].seq }}"
            static_v4:
                - 
                    dest: 0.0.0.0/0
                    nh: "{{ edge_netv4|ansible.utils.ipsubnet(edge_netmaskv4, edge_links_seq[0]) | ansible.utils.ipaddr(-2) | ansible.utils.ipaddr('address') }}"
                - 
                    dest: 0.0.0.0/0
                    nh: "{{ edge_netv4|ansible.utils.ipsubnet(edge_netmaskv4, edge_links_seq[1]) | ansible.utils.ipaddr(-2) | ansible.utils.ipaddr('address') }}"
            static_v6:
                - 
                    dest: 0::0/0
                    nh: "{{ edge_netv6|ansible.utils.ipsubnet(edge_netmaskv6, edge_links_seq[0]) | ansible.utils.ipaddr(-2) | ansible.utils.ipaddr('address') }}"
                - 
                    dest: 0::0/0
                    nh: "{{ edge_netv6|ansible.utils.ipsubnet(edge_netmaskv6, edge_links_seq[1]) | ansible.utils.ipaddr(-2) | ansible.utils.ipaddr('address') }}"
        rleak_rules:
            rmap_out: "BGP-VRF-LEAK-OUT-RED"
            rmap_in:
            rt_import: "{{ bgp.local_as }}:999"
            rt_export: "{{ bgp.local_as }}:999"
    - 
        name: "BLUE"
        desc: "BLUE_VRF"
        rd_pfx: "{{ lpbk1.addr_v4 }}"
        rt_pfx: "1002"
        l3_vni: 
          id: "9002"
          vlan: "902"
        interfaces:
        - 
            name: "loopback902"
            desc: "Loopback Interface"
            addr_v4: "10.10.202.{{ seq }}/32"
            addr_v6: 
        type5:
        - 
            r_map: 
            afi: ipv4
            proto: "connected"
    
