---
###################################################################
# General Data and Site Specific Data for all pods
###################################################################
sites:
# Site 01"
- name: sjc
  status: active
  asn: 65001
  time_zone: America/Los Angeles
  description: Arista Cluster for sjc
  physical_address: Santa Clara, CA, 95131
  shipping_address: Santa Clara, CA, 95131
  latitude: 37.354107
  longitude: -121.955238
  contact_name: Joe
  contact_phone: 867-5309
  contact_email: admin@sjc.arista.com
  region: uswest
  slug: sjc
  comments:  Placeholder
  vlans:
  - name: ADMIN
    tenant: internal
    vid: 901
    prefix: 10.1.4.0/26
    status: active
  - name: SERVERS
    tenant: internal
    vid: 902
    prefix: 10.1.4.64/26
    status: active
  - name: NMS
    tenant: internal
    vid: 903
    prefix: 10.1.4.128/26
    status: active
  - name: NATIVE_VLAN
    tenant: internal
    vid: 904
    prefix: 10.1.4.192/26
    status: active
  - name: CustA_01
    tenant: custa
    vid: 105
    prefix: 10.1.12.0/24
    status: active
  - name: CustA_02
    tenant: custa
    vid: 106
    prefix: 10.1.13.0/24
    status: active
  racks:
  - name: sjc_rack_01
    rack_role: "compute"
    status: active
  - name: sjc_rack_02
    rack_role: "compute"
    status: active
  - name: sjc_rack_03
    rack_role: "compute"
    status: active
  - name: sjc_rack_04
    rack_role: "network"
    status: active
# Site 02"
- name: lax
  status: active
  asn: 65002
  time_zone: America/Los Angeles
  description: Arista Cluster for lax
  physical_address: Los Angeles, CA, 90012
  shipping_address: Los Angeles, CA, 90012
  latitude: 34.0549
  longitude: -118.2426
  contact_name: Joe
  contact_phone: 867-5309
  contact_email: admin@lax.arista.com
  region: uswest
  slug: lax
  comments: 
  vlans:
  - name: ADMIN
    tenant: internal
    vid: 901
    prefix: 10.2.4.0/26
    status: active
  - name: SERVERS
    tenant: internal
    vid: 902
    prefix: 10.2.4.64/26
    status: active
  - name: NMS
    tenant: internal
    vid: 903
    prefix: 10.2.4.128/26
    status: active
  - name: NATIVE_VLAN
    tenant: internal
    vid: 904
    prefix: 10.2.4.192/26
    status: active
  - name: CustA_01
    tenant: custa
    vid: 105
    prefix: 10.2.12.0/24
    status: active
  - name: CustA_02
    tenant: custa
    vid: 106
    prefix: 10.2.13.0/24
    status: active
  racks:
  - name: lax_rack_01
    rack_role: "compute"
    status: active
  - name: lax_rack_02
    rack_role: "compute"
    status: active
  - name: lax_rack_03
    rack_role: "compute"
    status: active
  - name: lax_rack_04
    rack_role: "network"
    status: active
# Site 03"
- name: Cloud_AWS01
  status: active
  asn: 400
  time_zone: 
  description: Cloud Instances
  physical_address: 
  shipping_address: 
  latitude: 
  longitude: 
  contact_name: cloudadmin
  contact_phone: 878-8238
  contact_email: cloudadmin@arista.com
  region: 
  slug: cloud
  comments: cloud instance
