connections:
- name: sjcr1
  interface:
  - name: GigabitEthernet0/1
    bside_device: sjcsw1
    bside_port: GigabitEthernet0/0 
  - name: GigabitEthernet0/2
    bside_device: sjcsw2
    bside_port: GigabitEthernet0/0  
- name: sjcsw1
  interface: 
  - name: GigabitEthernet0/1
    bside_device: sjcsw2
    bside_port: GigabitEthernet0/1
  - name: GigabitEthernet0/2
    bside_device: sjcsw2
    bside_port: GigabitEthernet0/2  
  - name: GigabitEthernet0/3
    bside_device: sjcsw3
    bside_port: GigabitEthernet0/1
- name: sjcsw2
  interface:
  - name: GigabitEthernet0/3
    bside_device: sjcsw3
    bside_port: GigabitEthernet0/2
- name: laxr1
  interface:
  - name: GigabitEthernet0/1
    bside_device: laxsw1
    bside_port: GigabitEthernet0/0
  - name: GigabitEthernet0/2
    bside_device: laxsw2
    bside_port: GigabitEthernet0/0  
- name: laxsw1
  interface:
  - name: GigabitEthernet0/1
    bside_device: laxsw2
    bside_port: GigabitEthernet0/1
  - name: GigabitEthernet0/2
    bside_device: laxsw2
    bside_port: GigabitEthernet0/2  
  - name: GigabitEthernet0/3
    bside_device: laxsw3
    bside_port: GigabitEthernet0/1
- name: laxsw2
  interface:
  - name: GigabitEthernet0/3
    bside_device: laxsw3
    bside_port: GigabitEthernet0/2
- name: bosr1
  interface:
  - name: GigabitEthernet0/1
    bside_device: bossw1
    bside_port: GigabitEthernet0/0
  - name: GigabitEthernet0/2
    bside_device: bossw2
    bside_port: GigabitEthernet0/0  
- name: bossw1
  interface:
  - name: GigabitEthernet0/1
    bside_device: bossw2
    bside_port: GigabitEthernet0/1
  - name: GigabitEthernet0/2
    bside_device: bossw2
    bside_port: GigabitEthernet0/2  
  - name: GigabitEthernet0/3
    bside_device: bossw3
    bside_port: GigabitEthernet0/1
- name: bossw2
  interface:
  - name: GigabitEthernet0/3
    bside_device: bossw3
    bside_port: GigabitEthernet0/2
- name: lasr1
  interface:
  - name: GigabitEthernet0/1
    bside_device: lassw1
    bside_port: GigabitEthernet0/0
  - name: GigabitEthernet0/2
    bside_device: lassw2
    bside_port: GigabitEthernet0/0  
- name: lassw1
  interface:
  - name: GigabitEthernet0/1
    bside_device: lassw2
    bside_port: GigabitEthernet0/1
  - name: GigabitEthernet0/2
    bside_device: lassw2
    bside_port: GigabitEthernet0/2  
  - name: GigabitEthernet0/3
    bside_device: lassw3
    bside_port: GigabitEthernet0/1
- name: lassw2
  interface:
  - name: GigabitEthernet0/3
    bside_device: lassw3
    bside_port: GigabitEthernet0/2
- name: atlr1
  interface:
  - name: GigabitEthernet0/1
    bside_device: atlsw1
    bside_port: GigabitEthernet0/0
  - name: GigabitEthernet0/2
    bside_device: atlsw2
    bside_port: GigabitEthernet0/0  
- name: atlsw1
  interface:
  - name: GigabitEthernet0/1
    bside_device: atlsw2
    bside_port: GigabitEthernet0/1
  - name: GigabitEthernet0/2
    bside_device: atlsw2
    bside_port: GigabitEthernet0/2  
  - name: GigabitEthernet0/3
    bside_device: atlsw3
    bside_port: GigabitEthernet0/1
- name: atlsw2
  interface:
  - name: GigabitEthernet0/3
    bside_device: atlsw3
    bside_port: GigabitEthernet0/2
- name: mcir1
  interface:
  - name: GigabitEthernet0/1
    bside_device: mcisw1
    bside_port: GigabitEthernet0/0
  - name: GigabitEthernet0/2
    bside_device: mcisw2
    bside_port: GigabitEthernet0/0  
- name: mcisw1
  interface:
  - name: GigabitEthernet0/1
    bside_device: mcisw2
    bside_port: GigabitEthernet0/1
  - name: GigabitEthernet0/2
    bside_device: mcisw2
    bside_port: GigabitEthernet0/2  
  - name: GigabitEthernet0/3
    bside_device: mcisw3
    bside_port: GigabitEthernet0/1
- name: mcisw2
  interface:
  - name: GigabitEthernet0/3
    bside_device: mcisw3
    bside_port: GigabitEthernet0/2
- name: cloud_router
  interface:
  - name: GigabitEthernet1
    bside_device: sjcr1
    bside_port: GigabitEthernet0/0
  - name: GigabitEthernet2
    bside_device: laxr1
    bside_port: GigabitEthernet0/0
  - name: GigabitEthernet3
    bside_device: bosr1
    bside_port: GigabitEthernet0/0
  - name: GigabitEthernet4
    bside_device: lasr1
    bside_port: GigabitEthernet0/0
  - name: GigabitEthernet5
    bside_device: atlr1
    bside_port: GigabitEthernet0/0
  - name: GigabitEthernet6
    bside_device: mcir1
    bside_port: GigabitEthernet0/0     