local_context:
  - name: sjcr1
    bgp:
      address_family_ipv4:
        advertised_networks:
          - 10.1.1.0/26
          - 10.2.1.0/26
          - 10.1.1.64/26
        agg_network: 
          - 10.1.1.0/24
      ebgp:
        neighbors:
          24.24.1.1:
            r_asn: 400
      ibgp:
        l_asn: 65001
        neighbors:
        - 10.0.1.2
        - 10.0.1.3
  - name: sjcsw1
    bgp:
      address_family_ipv4:
        advertised_networks:
          - 10.1.1.0/26
          - 10.2.1.0/26
          - 10.1.1.64/26
      ibgp:
        l_asn: 65001
        neighbors:
        - 10.0.1.1
        - 10.0.1.3
  - name: sjcsw2
    bgp:
      address_family_ipv4:
        advertised_networks:
          - 10.1.1.0/26
          - 10.2.1.0/26
          - 10.1.1.64/26
      ibgp:
        l_asn: 65001
        neighbors:
        - 10.0.1.1
        - 10.0.1.2
  - name: laxr1
    bgp:
      address_family_ipv4:
        advertised_networks:
          - 10.1.2.0/26
          - 10.2.2.0/24
          - 10.1.2.64/24
        agg_network:
          - 10.1.2.0/24
      ebgp:
        neighbors:
          24.24.2.1:
            r_asn: 400
      ibgp:
        l_asn: 65002
        neighbors:
        - 10.0.2.2
        - 10.0.2.3
  - name: laxsw1
    bgp:
      address_family_ipv4:
        advertised_networks:
          - 10.1.2.0/26
          - 10.2.2.0/24
          - 10.1.2.64/24
      ibgp:
        l_asn: 65002
        neighbors:
        - 10.0.2.1
        - 10.0.2.3
  - name: laxsw2
    bgp:
      address_family_ipv4:
        advertised_networks:
          - 10.1.2.0/26
          - 10.2.2.0/24
          - 10.1.2.64/24
      ibgp:
        l_asn: 65002
        neighbors:
        - 10.0.2.1
        - 10.0.2.2
  - name: bosr1
    bgp:
      address_family_ipv4:
        advertised_networks:
          - 10.1.3.0/26
          - 10.2.3.0/26
          - 10.1.3.64/26
        agg_network:
          - 10.1.3.0/24
      ebgp:
        neighbors:
          24.24.3.1:
            r_asn: 400
      ibgp:
        l_asn: 65003
        neighbors:
        - 10.0.3.2
        - 10.0.3.3
  - name: bossw1
    bgp:
      address_family_ipv4:
        advertised_networks:
          - 10.1.3.0/26
          - 10.2.3.0/26
          - 10.1.3.64/26
      ibgp:
        l_asn: 65003
        neighbors:
        - 10.0.3.1
        - 10.0.3.3
  - name: bossw2
    bgp:
      address_family_ipv4:
        advertised_networks:
          - 10.1.3.0/26
          - 10.2.3.0/26
          - 10.1.3.64/26
      ibgp:
        l_asn: 65003
        neighbors:
        - 10.0.3.1
        - 10.0.3.2
  - name: lasr1
    bgp:
      address_family_ipv4:
        advertised_networks:
          - 10.1.4.0/26
          - 10.2.4.0/26
          - 10.1.4.64/26
        agg_network:
          - 10.1.4.0/24
      ebgp:
        neighbors:
          24.24.4.1:
            r_asn: 400
      ibgp:
        l_asn: 65004
        neighbors:
        - 10.0.4.2
        - 10.0.4.3
  - name: lassw1
    bgp:
      address_family_ipv4:
        advertised_networks:
          - 10.1.4.0/26
          - 10.2.4.0/26
          - 10.1.4.64/26
      ibgp:
        l_asn: 65004
        neighbors:
        - 10.0.4.1
        - 10.0.4.3
  - name: lassw2
    bgp:
      address_family_ipv4:
        advertised_networks:
          - 10.1.4.0/26
          - 10.2.4.0/26
          - 10.1.4.64/26
      ibgp:
        l_asn: 65004
        neighbors:
        - 10.0.4.1
        - 10.0.4.2
  - name: atlr1
    bgp:
      address_family_ipv4:
        advertised_networks:
          - 10.1.5.0/26
          - 10.2.5.0/26
          - 10.1.5.64/26
        agg_network:
          - 10.1.5.0/24
      ebgp:
        neighbors:
          24.24.5.1:
            r_asn: 400
      ibgp:
        l_asn: 65005
        neighbors:
        - 10.0.5.2
        - 10.0.5.3
  - name: atlsw1
    bgp:
      address_family_ipv4:
        advertised_networks:
          - 10.1.5.0/26
          - 10.2.5.0/26
          - 10.1.5.64/26
      ibgp:
        l_asn: 65005
        neighbors:
        - 10.0.5.1
        - 10.0.5.3
  - name: atlsw2
    bgp:
      address_family_ipv4:
        advertised_networks:
          - 10.1.5.0/26
          - 10.2.5.0/26
          - 10.1.5.64/26
      ibgp:
        l_asn: 65005
        neighbors:
        - 10.0.5.1
        - 10.0.5.2
  - name: mcir1
    bgp:
      address_family_ipv4:
        advertised_networks:
          - 10.1.6.0/26
          - 10.2.6.0/26
          - 10.1.6.64/26
        agg_network:
          - 10.1.6.0/24
      ebgp:
        neighbors:
          24.24.6.1:
            r_asn: 400
      ibgp:
        l_asn: 65006
        neighbors:
        - 10.0.6.2
        - 10.0.6.3
  - name: mcisw1
    bgp:
      address_family_ipv4:
        advertised_networks:
          - 10.1.6.0/26
          - 10.2.6.0/26
          - 10.1.6.64/26
      ibgp:
        l_asn: 65006
        neighbors:
        - 10.0.6.1
        - 10.0.6.3
  - name: mcisw2
    bgp:
      address_family_ipv4:
        advertised_networks:
          - 10.1.6.0/26
          - 10.2.6.0/26
          - 10.1.6.64/26
      ibgp:
        l_asn: 65006
        neighbors:
        - 10.0.6.1
        - 10.0.6.2                       