---
###################################################################
# General Data and Site Specific Data for all pods
###################################################################
sites:
- name: sjc
  status: active
  asn: 65001
  time_zone: "America/Los Angeles"
  description: "Arista Cluster for sjc"
  physical_address: "Santa Clara, CA, 95131"
  shipping_address: "Santa Clara, CA, 95131"
  latitude: "37.354107"
  longitude: "-121.955238"
  contact_name: Joe
  contact_phone: "867-5309"
  contact_email: "admin@sjc.arista.com"
  facility: EquinoxCA1
  region: uswest
  slug: sjc
  comments: " Placeholder"
  int_prefixes:
  - prefix: 10.10.1.0/31
    description: "R1-GI0/1 - SW1-GI0/0"
  - prefix: 10.10.1.2/31
    description: "R1-GI0/2 - SW2-GI0/0"
  - prefix: 24.24.1.0/24
    description: "R1-GI0/0 - INTERNET"
  vlans:
  - name: ADMIN
    tenant: "internal"
    status: active
  - name: SERVERS
    tenant: "internal"
    status: active
  - name: NMS
    tenant: "internal"
    status: active
  - name: NATIVE_VLAN
    tenant: "internal"
    status: active
  - name: CustA_01
    tenant: "custa"
    status: active
  - name: CustA_02
    tenant: "custa"
    status: active
  racks:
  - role: compute
    rack_list: [1,2,3]
    status: active
  - role: network
    rack_list: [4]
    status: active
# Site 2
- name: lax
  status: active
  asn: 65002
  time_zone: "America/Los Angeles"
  description: "Arista Cluster for lax"
  physical_address: "Los Angeles, CA, 90012"
  shipping_address: "Los Angeles, CA, 90012"
  latitude: "34.0549"
  longitude: "-118.2426"
  contact_name: Joe
  contact_phone: "867-5309"
  contact_email: "admin@lax.arista.com"
  facility: PNAPLA01
  region: uswest
  slug: lax
  int_prefixes:
  - prefix: 10.10.2.0/31
    description: "R1-GI0/1 - SW1-GI0/0"
  - prefix: 10.10.2.2/31
    description: "R1-GI0/2 - SW2-GI0/0"
  - prefix: 24.24.2.0/24
    description: "R1-GI0/0 - INTERNET"  
  vlans:
  - name: ADMIN
    tenant: "internal"
    status: active
  - name: SERVERS
    tenant: "internal"
    status: active
  - name: NMS
    tenant: "internal"
    status: passive
  - name: NATIVE_VLAN
    tenant: "internal"
    status: active
  - name: CustA_01
    tenant: "custa"
    status: active
  - name: CustA_02
    tenant: "custa"
    status: active
  racks:
  - role: compute
    rack_list: [1,2,3]
    status: active
  - role: network
    rack_list: [4]
    status: active
# Special Sites
# - name: "Cloud_AWS01"
#   status: "active"
#   asn: "400"
#   description: "Cloud Instances"
#   contact_name: "cloudadmin"
#   contact_phone: "878-8238"
#   contact_email: "cloudadmin@arista.com"
#   facility: AWS-West-01
#   slug: "cloud"
#   comments: "cloud instance"
#   state: present
