---
- hosts: ceos
  collections:
     - arista.eos
    
  tasks:
  # - name: Install roles from Ansible Galaxy
  #   command: "ansible-galaxy collection install arista.eos"
  #   delegate_to: localhost
  #   run_once: yes
  #   tags: install

  - name: Get Switch current OS version
    # gather_facts: true
    eos_facts:
      gather_subset: 
      - hardware
    register: pre_facts
    tags: facts

  - name: Display EoS Version
    debug:
      msg: "The version is {{ pre_facts.ansible_facts.ansible_net_version }}"
    tags: facts

  # - name: Enable Service under mgmt VRF
  #   eos_config:
  #     commands:
  #       - command: ip {{ item }} vrf MGMT
  #         prompt: ']:'
  #         answer: 'yes'
  #   loop:
  #     - "http"
  #     - "scp"
  #     - "ftp"
  #   tags: enable_vrf

    # Only uploading to switches where current version is not at required version 
  # - name: Upload image to Switch
  #   include_role: 
  #     name: Dell-Networking.dellos-image-upgrade
  #     apply:
  #       tags:
  #         - install
  #   when: dellos_image_upgrade.software_version != pre_facts.ansible_facts.ansible_net_version
  #   tags: install

  - name: Generate the intial configuration
    template:
        src: ceos/initial_cfg.j2
        dest: "ztp/{{hostname}}.conf.init"
    tags:
    - cfggen