---
- hosts: ceos
  gather_facts: false
  vars:
      temp_file: "dummy_lpbk.j2"
      save_dir: "{{ build_dir }}"
      round: 1
      # save_dir: "files"
  collections:
  - arista.eos

  tasks:
  - name: Generate the templated config
    vars:
        round: "{{ item }}"
    template:
      src: "{{ temp_file }}"
      dest: "{{save_dir}}/{{hostname}}.conf.part.{{round}}"
    # delegate_to: localhost
    with_items: [0,1]
    tags:
      - cfggen

  - name: Display the generated config
    debug: var=item
    with_file:
      - "{{save_dir}}/{{hostname}}.conf.part.0"
    tags:
      - cfggen

  - name: Push the templated config
    vars:
        ansible_command_timeout: 900
        # round: "{{ item }}"
    eos_config:
      src: "{{ temp_file }}"
    # with_items: [5,6,7,8,9]
    tags:
    - cfgpush
