---
- hosts: poc
  gather_facts: false
  collections:
  - arista.eos

  tasks:
  - name: Change Hostname
    arista.eos.eos_hostname:
      config:
        hostname: "{{ inventory_hostname }}"
      state: merged
    tags:
      - hostname

  - name: Enable Network Services
    vars:
      ansible_command_timeout: 60
    block:
    - name: Enable IP Routing
      eos_config:
        lines: 
        - ip routing
        - ipv6 unicast-routing
        - ip routing vrf MGMT
      tags:
        - routing

    # - name: Enable Domain/DNS Server
    #   eos_config:
    #     src: domain.j2
    #     # diff_against: validate_config
    #     # intended_config: "/home/xji/devops/cfggen/{{hostname}}.conf.part"
    #   tags:
    #     - domain

    - name: Enable Banner Motd
      eos_banner:
        banner: motd
        text: "{{ lookup('file', 'files/banner_motd') }}"
        state: present
      tags:
        - banner

    - name: Enable Banner Login
      eos_banner:
        banner: login
        text: "{{ lookup('file', 'files/banner_login') }}"
        state: present
      tags:
        - banner

    - name: Setup the local user accounts
      block:
      - name: Enable all local users
        eos_config:
          src: user.j2

      - name: Add SSHKEY for Ansible user
        arista.eos.eos_user:
          name: ansible
          sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
          state: present

      tags:
        - users

    # - name: Enable NTP
    #   eos_config:
    #       src: ntp.j2
    #   # when: (features.netserv.ntp is defined and features.netserv.ntp|lower == "yes")
    #   tags:
    #     - ntp

    # - name: Enable Syslog
    #   eos_config:
    #       src: syslog.j2
    #   # when: (features.netserv.syslog is defined and features.netserv.syslog|lower == "yes")
    #   tags:
    #   - syslog

    # - name: Enable SNMP
    #   eos_config:
    #       src: snmp.j2
    #   when: (features.netserv.snmp is defined and features.netserv.snmp|lower == "yes")
    #   tags:
    #   - snmp

    # - name: Enable Group & AAA
    #   block:
    #   - name: Enable Tacacs
    #     eos_config:
    #         src: tacacs.j2
    #     # when: (features.netserv.tacacs is defined and features.netserv.tacacs|lower == "yes")
    #   - name: Enable Radius
    #     eos_config:
    #         src: radius.j2
    #     # when: (features.netserv.radius is defined and features.netserv.radius|lower == "yes")
    #   - name: Enable AAA
    #     eos_config:
    #         src: aaa.j2
    #     # when: (features.netserv.aaa is defined and features.netserv.aaa|lower == "yes")
    #   tags:
    #     - aaa
    tags:
      - netserv

- hosts: poc_leaf
  gather_facts: false
  collections:
  - arista.eos

  tasks:
  - name: Enable loopback Interface
    eos_config:
        src: intf_lpbk.j2
    tags:
    - loopback

  - name: Enable Leaf/Spine PTP Interface
    eos_config:
        src: intf_ptp.j2
    tags:
    - ptp

  - name: Enable Southbound L2/MLAG/Trunk Interface
    block:
    - name: Enable Layer2 Port
      eos_config:
          src: intf_l2.j2
      when: (features.interface.l2port is defined and features.interface.l2port|lower == "yes")

    - name: Enable MLAG Domain
      eos_config:
          src: mlag.j2
      when: (features.interface.mlag is defined and features.interface.mlag|lower == "yes")
      tags:
        - mlag
    - name: Enable Bond and Trunking
      eos_config:
          src: intf_bond.j2
      when: (features.interface.bond is defined and features.interface.bond|lower == "yes")
      ignore_errors: yes
    when: "'leaf' in inventory_hostname"
    tags:
      - l2port

  - name: Enable Routing Policy on LEAF
    eos_config:
        src: route_pol.j2
    when: "'leaf' in inventory_hostname"
    tags:
      - rpol

  - name: Enable Standard BGP on Leaf
    eos_config:
        src: bgp_underlay_leaf.j2
    when: "'leaf' in inventory_hostname"
    tags:
    - standard

  - name: Enable Vxlan Tunneling
    eos_config:
        src: vxlan.j2
    tags:
      - vxlan

  - name: Enable EVPN Routing
    eos_config:
        src: vrf_routing.j2
    tags:
      - vrf_routing

- hosts: poc_spine
  gather_facts: false
  collections:
  - arista.eos

  tasks:
  - name: Enable Leaf/Spine PTP Interface
    eos_config:
        src: intf_ptp_spine.j2
    tags:
    - ptp

  - name: Enable Standard BGP on Spine
    eos_config:
        src: bgp_underlay_spine.j2
    when: (features.routing.bgp_stan|lower == "yes")
    tags:
    - standard
