---
- hosts: ceos
  gather_facts: false
  vars:
      temp_file: "dummy_lpbk.j2"
      save_dir: "{{ build_dir }}"
      # save_dir: "files"
  collections:
  - arista.eos

  tasks:
  - name: Generate the templated config
    template:
      src: "{{ temp_file }}"
      dest: "{{save_dir}}/{{hostname}}.conf.part"
    # delegate_to: localhost
    tags:
      - cfggen

  - name: Display the generated config
    debug: var=item
    with_file:
      - "{{save_dir}}/{{hostname}}.conf.part"
    tags:
      - cfggen

  # - name: Generate the templated config
  #   eos_config:
  #     src: bgp_overlay_ibgp.j2
  #   tags:
  #   - cfgpush
