# requires ansible-galaxy collection install networktocode.nautobot & pip3 install pynautobot
---
- name: "Build Nautobot Load File"
  hosts: localhost
  connection: local
  gather_facts: False
  collections:
    - networktocode.nautobot

  vars_files:
  - /home/xji/devops/arista-naas/group_vars/dc2.yaml
  - inventory/nautobot_vars/sites.yaml
  - inventory/nautobot_vars/regions.yaml
  - inventory/nautobot_vars/vrfs.yaml
  - inventory/nautobot_vars/devices.yaml
  - inventory/nautobot_vars/_nodes_design.yaml
  - inventory/nautobot_vars/device_local_context.yaml
  - inventory/nautobot_vars/custom_fields.yaml
  - inventory/nautobot_vars/device_connections.yaml
      
  roles:
  - { role: create_load_file/site }
  - { role: create_load_file/node_design }

  # roles:
  # - { role: load_nautobot/create_rack }
  # - { role: load_nautobot/create_vlans }
  # - { role: load_nautobot/create_vrfs }
  # - { role: load_nautobot/create_prefixes }
  # - { role: load_nautobot/create_manufacturer }
  # - { role: load_nautobot/create_platform }
  # - { role: load_nautobot/create_device_types }
  # - { role: load_nautobot/create_device_roles }
  # - { role: load_nautobot/create_devices }
  # - { role: load_nautobot/create_access_interfaces }
  # - { role: load_nautobot/create_trunk_interfaces }
  # - { role: load_nautobot/create_lag_interfaces }
  # - { role: load_nautobot/create_l3_interfaces }
  # - { role: load_nautobot/create_disabled_interfaces }
  # - { role: load_nautobot/assign_ipv4_to_interfaces }
  # - { role: load_nautobot/create_tags }
  # # - { role: load_nautobot/create_cables }