# requires ansible-galaxy collection install networktocode.nautobot & pip3 install pynautobot
---
- name: "Setup Nautobot"
  hosts: localhost
  connection: local
  gather_facts: False
  collections:
    - networktocode.nautobot

  vars_files:
   - inventory/nautobot_vars/site.yaml
   - inventory/nautobot_vars/tags.yaml
   - inventory/nautobot_vars/vrfs.yaml
   - inventory/nautobot_vars/devices.yaml
   - inventory/nautobot_vars/node_design.yaml
   - inventory/nautobot_vars/device_local_context.yaml
   - inventory/nautobot_vars/custom_fields.yaml
   - inventory/nautobot_vars/device_connections.yaml

  tasks:
  - name: Create site with all parameters
    networktocode.nautobot.site:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      validate_certs: no
      name: "{{ item.name }}"
      status: "{{ item.status }}"
      asn: "{{ item.asn }}"
      time_zone: "{{ item.time_zone }}"
      description: "{{ item.description }}"
      physical_address: "{{ item.physical_address }}"
      shipping_address: "{{ item.shipping_address }}"
      latitude: "{{ item.latitude }}"
      longitude: "{{ item.longitude }}"
      contact_name: "{{ item.contact_name }}"
      contact_phone: "{{ item.contact_phone }}"
      contact_email: "{{ item.contact_email }}"
      slug: "{{ item.slug }}"
      comments: "{{ item.comments }}"
      state: present
    loop: "{{ sites }}"

  # roles:
  # - { role: load_nautobot/create_rack }
  # - { role: load_nautobot/create_vlans }
  # - { role: load_nautobot/create_vrfs }
  # - { role: load_nautobot/create_prefixes }
  # - { role: load_nautobot/create_manufacturer }
  # - { role: load_nautobot/create_platform }
  # - { role: load_nautobot/create_device_types }
  # - { role: load_nautobot/create_device_roles }
  # - { role: load_nautobot/create_devices }
  # - { role: load_nautobot/create_access_interfaces }
  # - { role: load_nautobot/create_trunk_interfaces }
  # - { role: load_nautobot/create_lag_interfaces }
  # - { role: load_nautobot/create_l3_interfaces }
  # - { role: load_nautobot/create_disabled_interfaces }
  # - { role: load_nautobot/assign_ipv4_to_interfaces }
  # - { role: load_nautobot/create_tags }
  # # - { role: load_nautobot/create_cables }