---
- hosts: localhost
  # connection: local
  gather_facts: false
  # vars:
  #   url: "http://10.92.59.139:8000"
  #   token: "47942ba1733978d2842528ae15e028a59b70f69b"
  collections:
  - networktocode.nautobot

  vars_files:
   - inventory/nautobot_vars/regions.yaml
   - inventory/nautobot_vars/_sites.yaml
   - inventory/nautobot_vars/tenants.yaml
   - inventory/nautobot_vars/tags.yaml
   - inventory/nautobot_vars/vrfs.yaml
   - inventory/nautobot_vars/devices.yaml
   - inventory/nautobot_vars/_nodes_design.yaml
   - inventory/nautobot_vars/device_local_context.yaml
   - inventory/nautobot_vars/custom_fields.yaml
   - inventory/nautobot_vars/device_connections.yaml

  roles:
  - { role: load_nautobot/create_region }
  - { role: load_nautobot/create_site }
  - { role: load_nautobot/create_tenant }
  - { role: load_nautobot/create_rack }
  - { role: load_nautobot/create_vlans }
  - { role: load_nautobot/create_vrfs }
  - { role: load_nautobot/create_prefixes }
  - { role: load_nautobot/create_manufacturer }
  - { role: load_nautobot/create_platform }
  - { role: load_nautobot/create_device_types }
  - { role: load_nautobot/create_device_roles }
  - { role: load_nautobot/create_devices }

  - { role: load_nautobot/create_interfaces_access }
  - { role: load_nautobot/create_interfaces_trunk }
  - { role: load_nautobot/create_interfaces_lag }
  - { role: load_nautobot/create_interfaces_l3 }
  # - { role: load_nautobot/create_access_interfaces }
  # - { role: load_nautobot/create_trunk_interfaces }
  # - { role: load_nautobot/create_lag_interfaces }
  # - { role: load_nautobot/create_l3_interfaces }
  # - { role: load_nautobot/create_disabled_interfaces }
  # - { role: load_nautobot/assign_ipv4_to_interfaces }
  # - { role: load_nautobot/create_tags }
  # # - { role: load_nautobot/create_cables }

#   tasks:
#   - name: Add Devices
#     networktocode.nautobot.device:
#       url: "{{ nb_url }}"
#       token: "{{ nb_token }}"
#       validate_certs: no
#       name: "{{ item.name }}"
#       device_type: "{{ item.device_type }}"
#       device_role: "{{ item.device_role }}"
#       site: "{{ item.site }}"
#       rack: "{{ item.rack }}"
#       position: "{{ item.position }}"
#       face: "{{ item.face }}"
#       status: "{{ item.status }}"
#       state: present
#     loop: "{{ device_list }}"
#     tags:
#       - device

  # - { role: load_nautobot/create_disabled_interfaces }
  # - { role: load_nautobot/assign_ipv4_to_interfaces }
  # - { role: load_nautobot/create_tags }
  # # - { role: load_nautobot/create_cables }

  # - name: "Add Device to nautobot"
  #   device:
  #     url: "http://10.92.59.139:8000"
  #     token: "47942ba1733978d2842528ae15e028a59b70f69b"
  #     name: "{{ item.name }}"
  #     rack: "{{ item.rack }}"
  #     site: "{{ item.site }}"
  #     device_role: "{{ item.device_role }}"
  #     device_type: "{{ item.device_type }}"
  #     status: active
  #     state: present
  #   loop:
  #     - name: cleaf01
  #       rack: "Rack01"
  #       site: "Boston"
  #       device_role: "cleaf"
  #       device_type: "7050X3"
  #     - name: cleaf02
  #       rack: "Rack01"
  #       site: "Boston"
  #       device_role: "cleaf"
  #       device_type: "7050X3"
  #     - name: cleaf03
  #       rack: "Rack02"
  #       site: "Boston"
  #       device_role: "cleaf"
  #       device_type: "7050X3"
  #     - name: cleaf04
  #       rack: "Rack02"
  #       site: "Boston"
  #       device_role: "cleaf"
  #       device_type: "7050X3"
  #     - name: bleaf01
  #       rack: "Rack03"
  #       site: "Boston"
  #       device_role: "bleaf"
  #       device_type: "7280R3"
  #     - name: bleaf02
  #       rack: "Rack03"
  #       site: "Boston"
  #       device_role: "bleaf"
  #       device_type: "7280R3"
  #     - name: spine01
  #       rack: "Rack03"
  #       site: "Boston"
  #       device_role: "spine"
  #       device_type: "7060X4"
  #     - name: spine02
  #       rack: "Rack03"
  #       site: "Boston"
  #       device_role: "spine"
  #       device_type: "7060X4"
  #     - name: mleaf01
  #       rack: "Rack01"
  #       site: "Boston"
  #       device_role: "mleaf"
  #       device_type: "720XP"
  #   tags:
  #     - device


