---
- hosts: localhost
  # connection: local
  gather_facts: false
  # vars:
  #   url: "http://10.92.59.139:8000"
  #   token: "47942ba1733978d2842528ae15e028a59b70f69b"
  collections:
  - networktocode.nautobot

  vars_files:
   - inventory/nautobot_vars/regions.yaml
   - inventory/nautobot_vars/_sites.yaml
   - inventory/nautobot_vars/tenants.yaml
   - inventory/nautobot_vars/tags.yaml
   - inventory/nautobot_vars/vrfs.yaml
   - inventory/nautobot_vars/devices.yaml
   - inventory/nautobot_vars/_nodes_design.yaml
   - inventory/nautobot_vars/device_local_context.yaml
   - inventory/nautobot_vars/custom_fields.yaml
   - inventory/nautobot_vars/device_connections.yaml

  roles:
  - { role: load_nautobot/create_region }
  - { role: load_nautobot/create_site }
  - { role: load_nautobot/create_tenant }
  - { role: load_nautobot/create_rack }
  - { role: load_nautobot/create_vlans }
  - { role: load_nautobot/create_vrfs }
  - { role: load_nautobot/create_prefixes }
  - { role: load_nautobot/create_manufacturer }
  - { role: load_nautobot/create_platform }
  - { role: load_nautobot/create_device_types }
  - { role: load_nautobot/create_device_roles }
  - { role: load_nautobot/create_devices }
  - { role: load_nautobot/create_interfaces_access }
  - { role: load_nautobot/create_interfaces_trunk }
  - { role: load_nautobot/create_interfaces_lag }
  - { role: load_nautobot/create_interfaces_l3 }
  - { role: load_nautobot/create_interfaces_disabled }
  # - { role: load_nautobot/assign_ipv4_to_interfaces }
  - { role: load_nautobot/create_tags }
  - { role: load_nautobot/create_cables }
