---
- hosts: localhost
  # connection: local
  gather_facts: false
  # vars:
  #   url: "http://10.92.59.139:8000"
  #   token: "47942ba1733978d2842528ae15e028a59b70f69b"
  collections:
  - networktocode.nautobot

  vars_files:
   - /home/xji/devops/arista-naas/group_vars/dc2.yaml
   - inventory/nautobot_vars/regions.yaml
   - inventory/nautobot_vars/sites.yaml
   - inventory/nautobot_vars/tenants.yaml
   - inventory/nautobot_vars/tags.yaml
   - inventory/nautobot_vars/vrfs.yaml
   - inventory/nautobot_vars/devices.yaml
   - inventory/nautobot_vars/_nodes_design.yaml
   - inventory/nautobot_vars/device_local_context.yaml
   - inventory/nautobot_vars/custom_fields.yaml
   - inventory/nautobot_vars/device_connections.yaml

  tasks:
  - name: Create ROOT region
    region:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      name: "ROOT"
      slug: "root"
      state: present
    tags:
      - region

  - name: Create following regions
    region:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      name: "{{ item.name }}"
      parent_region: "{{ item.parent_region }}"
      slug: "{{ item.slug }}"
      state: present
    loop: "{{ regions }}"
    tags:
      - region

  - name: Create site with all parameters
    networktocode.nautobot.site:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      validate_certs: no
      name: "{{ item.name }}"
      status: "{{ item.status }}"
      asn: "{{ item.asn }}"
      time_zone: "{{ item.time_zone }}"
      description: "{{ item.description }}"
      physical_address: "{{ item.physical_address }}"
      shipping_address: "{{ item.shipping_address }}"
      latitude: "{{ item.latitude }}"
      longitude: "{{ item.longitude }}"
      contact_name: "{{ item.contact_name }}"
      contact_phone: "{{ item.contact_phone }}"
      contact_email: "{{ item.contact_email }}"
      region: "{{ item.region }}"
      slug: "{{ item.slug }}"
      comments: "{{ item.comments }}"
      state: present
    loop: "{{ sites }}"
    tags:
      - site

  - name: Create Specific Sites
    site:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      name: "Cloud"
      status: "active"
      asn: "400"
      description: "Cloud Instances"
      contact_name: "cloudadmin"
      contact_phone: "878-8238"
      contact_email: "cloudadmin@arista.com"
      facility: AWS-West-01
      slug: "cloud"
      comments: "cloud instance"
      state: present
    tags:
      - site

  - name: Create Tenants
    networktocode.nautobot.tenant:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      validate_certs: no
      name: "{{ item.name }}"
      description: "{{ item.description }}"
      slug: "{{ item.slug }}"
      comments: "{{ item.comments|default(omit) }}"
      state: present
    loop: "{{ tenants }}"
    tags:
      - tenant

  - name: Create rack role
    networktocode.nautobot.rack_role:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      name: "{{ item.name }}"
      color: "{{ item.color }}"
      state: present
    loop: 
      - name: Compute
        slug: compute
        color: 00FF00
      - name: Network
        slug: network
        color: FFFF00
    tags:
      - rack

  - name: Create new rack"
    networktocode.nautobot.rack:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      validate_certs: no
      name: "{{ item.1.name }}"
      site: "{{ item.0.slug }}"
      rack_role: "{{ item.1.rack_role }}"
      status: "{{ item.1.status }}"
      state: present
    loop: "{{ sites | subelements('racks', 'skip_missing=True') }}"  
    tags:
      - rack

  - name: Create vlans
    networktocode.nautobot.vlan:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      validate_certs: no
      name: "{{ item.1.name }}"
      vid: "{{ item.1.vid }}"
      site: "{{ item.0.slug }}"
      # prefix: "{{ item.1.prefix|default(omit) }}"
      tenant: "{{ item.1.tenant }}"
      status: "{{ item.1.status }}"
      state: present
    loop: "{{ sites | subelements('vlans', 'skip_missing=True') }}"
    tags:
      - vlan

#############################################################
# Create VRFs in Nautobot
#############################################################    
  - name: Create VRFs within Nautobot
    networktocode.nautobot.vrf:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      validate_certs: no
      name: "{{ item.name }}"
      description: "{{ item.description }}"
      tenant: "{{ item.tenant|default(omit) }}"
      enforce_unique: "{{ item.enforce_unique|default(false) }}"
      state: present
    loop: "{{ vrf }}"
    tags:
      - vrf

#############################################################
# Create prefixes for each VRF in Nautobot
#############################################################
  - name: Create prefixes and assign to VRFs within Nautobot
    networktocode.nautobot.prefix:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      validate_certs: no
      family: 4
      prefix: "{{ item.prefix }}"
      description: "{{ item.description }}"
      vrf: "{{ item.name }}"
      tenant: "{{ item.tenant|default(omit) }}"
      is_pool: true
      status: active
      state: present  
    loop: "{{ vrf }}"
    tags:
      - vrf

#############################################################
# Create Manufacturer in Nautobot
#############################################################    
  - name: Create manufacturer within Nautobot 
    networktocode.nautobot.manufacturer:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      validate_certs: no
      name: "{{ item.name }}"
      state: present
    loop: "{{ manufacturer }}"
    tags:
      - platform

#############################################################
# Create Platform in Nautobot
#############################################################   
  - name: Create platform within Nautobot with only required information
    networktocode.nautobot.platform:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      validate_certs: no
      name: "{{ item.1.name }}"
      manufacturer: "{{ item.0.name }}"
      napalm_driver: "{{ item.1.napalm_driver }}"
      state: present
    loop: "{{ manufacturer | subelements('platform', 'skip_missing=True') }}"
    tags:
      - platform

#############################################################
# Create Device Types in Nautobot
#############################################################     
  - name: Create device types  
    networktocode.nautobot.device_type:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      validate_certs: no
      slug: "{{ item.1.slug }}"
      model: "{{ item.1.name }}"
      manufacturer: "{{ item.0.name }}"
      part_number: "{{ item.1.part_number }}"
      u_height: "{{ item.1.u_height }}"
      is_full_depth: "{{ item.1.is_full_depth }}"
      comments: "{{ item.1.comments|default(omit) }}"
      state: present
    loop: "{{ manufacturer | subelements('device_types', 'skip_missing=True') }}"
    tags:
      - platform

#############################################################
# Create Device Roles in Nautobot
############################################################# 
  - name: Create device role within Nautobot
    networktocode.nautobot.device_role:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      validate_certs: no
      name: "{{ item.1.name }}"
      color: "{{ item.1.color }}"
      state: present
    loop: "{{ manufacturer | subelements('device_roles', 'skip_missing=True') }}"
    tags:
      - platform

#############################################################
# Create Devices in Nautobot
#############################################################
  - name: Building File to load nautobot
    template: 
      src: "node_design_load.j2"
      dest: "inventory/nautobot_vars/_nodes_design.yaml"
    tags:
      - build_node

  - name: Add Devices
    networktocode.nautobot.device:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      validate_certs: no
      name: "{{ item.name }}"
      device_type: "{{ item.device_type }}"
      device_role: "{{ item.device_role }}"
      site: "{{ item.site }}"
      rack: "{{ item.rack }}"
      position: "{{ item.position }}"
      face: "{{ item.face }}"
      status: "{{ item.status }}"
      state: present
    loop: "{{ device_list }}"
    tags:
      - device

  roles:
  - { role: load_nautobot/create_access_interfaces }
  - { role: load_nautobot/create_trunk_interfaces }
  - { role: load_nautobot/create_lag_interfaces }
  - { role: load_nautobot/create_l3_interfaces }
  # - { role: load_nautobot/create_disabled_interfaces }
  # - { role: load_nautobot/assign_ipv4_to_interfaces }
  # - { role: load_nautobot/create_tags }
  # # - { role: load_nautobot/create_cables }

  # - name: Create device role within Nautobot with only required information
  #   device_role:
  #     url: "http://10.92.59.139:8000"
  #     token: "47942ba1733978d2842528ae15e028a59b70f69b"
  #     name: "{{item}}"
  #     color: FFFFFF
  #     state: present
  #   loop:
  #     - cleaf
  #     - bleaf
  #     - spine
  #     - superspine
  #   tags:
  #     - drole

  # - name: Create manufacturer within Nautobot with only required information
  #   manufacturer:
  #     url: "http://10.92.59.139:8000"
  #     token: "47942ba1733978d2842528ae15e028a59b70f69b"
  #     name: "{{ item }}"
  #     state: present
  #     description: The test manufacturer
  #   loop:
  #     - arista
  #     - cisco
  #     - dell
  #     - juniper
  #   tags:
  #     - vendor

  # - name: Create device type within Nautobot with only required information
  #   device_type:
  #     url: "http://10.92.59.139:8000"
  #     token: "47942ba1733978d2842528ae15e028a59b70f69b"
  #     model: "{{ item.model }}"
  #     manufacturer: "{{ item.vendor }}"
  #     state: present
  #   loop:
  #     - vendor: arista
  #       model: 7050X3
  #     - vendor: arista
  #       model: 7060X4
  #     - vendor: arista
  #       model: 7050X4
  #     - vendor: arista
  #       model: 7280R3
  #     - vendor: juniper
  #       model: qfx5700
  #     - vendor: juniper
  #       model: qfx5120
  #     - vendor: dell
  #       model: S5448F-ON
  #     - vendor: dell
  #       model: S5232F-ON
  #     - vendor: dell
  #       model: S5248F-ON
  #   tags:
  #     - dtype

  # - name: Create rack within Nautobot with only required information
  #   networktocode.nautobot.rack:
  #     url: "http://10.92.59.139:8000"
  #     token: "47942ba1733978d2842528ae15e028a59b70f69b"
  #     name: "{{ item.name }}"
  #     site: "{{ item.site }}"
  #     status: active
  #     state: present
  #   loop:
  #     - name: Rack01
  #       site: Boston
  #     - name: Rack02
  #       site: Boston
  #     - name: Rack03
  #       site: Boston
  #     - name: Rack04
  #       site: Boston
  #   tags:
  #     - rack

  # - name: "Add Device to nautobot"
  #   device:
  #     url: "http://10.92.59.139:8000"
  #     token: "47942ba1733978d2842528ae15e028a59b70f69b"
  #     name: "{{ item.name }}"
  #     rack: "{{ item.rack }}"
  #     site: "{{ item.site }}"
  #     device_role: "{{ item.device_role }}"
  #     device_type: "{{ item.device_type }}"
  #     status: active
  #     state: present
  #   loop:
  #     - name: cleaf01
  #       rack: "Rack01"
  #       site: "Boston"
  #       device_role: "cleaf"
  #       device_type: "7050X3"
  #     - name: cleaf02
  #       rack: "Rack01"
  #       site: "Boston"
  #       device_role: "cleaf"
  #       device_type: "7050X3"
  #     - name: cleaf03
  #       rack: "Rack02"
  #       site: "Boston"
  #       device_role: "cleaf"
  #       device_type: "7050X3"
  #     - name: cleaf04
  #       rack: "Rack02"
  #       site: "Boston"
  #       device_role: "cleaf"
  #       device_type: "7050X3"
  #     - name: bleaf01
  #       rack: "Rack03"
  #       site: "Boston"
  #       device_role: "bleaf"
  #       device_type: "7280R3"
  #     - name: bleaf02
  #       rack: "Rack03"
  #       site: "Boston"
  #       device_role: "bleaf"
  #       device_type: "7280R3"
  #     - name: spine01
  #       rack: "Rack03"
  #       site: "Boston"
  #       device_role: "spine"
  #       device_type: "7060X4"
  #     - name: spine02
  #       rack: "Rack03"
  #       site: "Boston"
  #       device_role: "spine"
  #       device_type: "7060X4"
  #     - name: mleaf01
  #       rack: "Rack01"
  #       site: "Boston"
  #       device_role: "mleaf"
  #       device_type: "720XP"
  #   tags:
  #     - device


