---
- hosts: localhost
  # connection: local
  gather_facts: false
  # vars:
  #   url: "http://10.92.59.139:8000"
  #   token: "47942ba1733978d2842528ae15e028a59b70f69b"
  collections:
  - networktocode.nautobot

  vars_files:
   - inventory/nautobot_vars/regions.yaml
   - inventory/nautobot_vars/sites.yaml
   - inventory/nautobot_vars/tags.yaml
   - inventory/nautobot_vars/vrfs.yaml
   - inventory/nautobot_vars/devices.yaml
   - inventory/nautobot_vars/nodes_design.yaml
   - inventory/nautobot_vars/device_local_context.yaml
   - inventory/nautobot_vars/custom_fields.yaml
   - inventory/nautobot_vars/device_connections.yaml

  tasks:
  - name: Create ROOT region
    region:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      name: "ROOT"
      slug: "root"
      state: present
    tags:
      - region

  - name: Create following regions
    region:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      name: "{{ item.name }}"
      parent_region: "{{ item.parent_region }}"
      slug: "{{ item.slug }}"
      state: present
    loop: "{{ regions }}"
    tags:
      - region

  - name: Create site with all parameters
    networktocode.nautobot.site:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      validate_certs: no
      name: "{{ item.name }}"
      status: "{{ item.status }}"
      asn: "{{ item.asn }}"
      time_zone: "{{ item.time_zone }}"
      description: "{{ item.description }}"
      physical_address: "{{ item.physical_address }}"
      shipping_address: "{{ item.shipping_address }}"
      latitude: "{{ item.latitude }}"
      longitude: "{{ item.longitude }}"
      contact_name: "{{ item.contact_name }}"
      contact_phone: "{{ item.contact_phone }}"
      contact_email: "{{ item.contact_email }}"
      slug: "{{ item.slug }}"
      comments: "{{ item.comments }}"
      state: absent
    loop: "{{ sites }}"
    tags:
      - site

  - name: Create site within Nautobot with only required information
    site:
      url: "{{ nb_url }}"
      token: "{{ nb_token }}"
      name: Boston
      region: "Northeasten"
      status: active
      state: present
    # tags:
    #   - site

  - name: Create device role within Nautobot with only required information
    device_role:
      url: "http://10.92.59.139:8000"
      token: "47942ba1733978d2842528ae15e028a59b70f69b"
      name: "{{item}}"
      color: FFFFFF
      state: present
    loop:
      - cleaf
      - bleaf
      - spine
      - superspine
    tags:
      - drole

  - name: Create manufacturer within Nautobot with only required information
    manufacturer:
      url: "http://10.92.59.139:8000"
      token: "47942ba1733978d2842528ae15e028a59b70f69b"
      name: "{{ item }}"
      state: present
      description: The test manufacturer
    loop:
      - arista
      - cisco
      - dell
      - juniper
    tags:
      - vendor

  - name: Create device type within Nautobot with only required information
    device_type:
      url: "http://10.92.59.139:8000"
      token: "47942ba1733978d2842528ae15e028a59b70f69b"
      model: "{{ item.model }}"
      manufacturer: "{{ item.vendor }}"
      state: present
    loop:
      - vendor: arista
        model: 7050X3
      - vendor: arista
        model: 7060X4
      - vendor: arista
        model: 7050X4
      - vendor: arista
        model: 7280R3
      - vendor: juniper
        model: qfx5700
      - vendor: juniper
        model: qfx5120
      - vendor: dell
        model: S5448F-ON
      - vendor: dell
        model: S5232F-ON
      - vendor: dell
        model: S5248F-ON
    tags:
      - dtype

  - name: Create rack within Nautobot with only required information
    networktocode.nautobot.rack:
      url: "http://10.92.59.139:8000"
      token: "47942ba1733978d2842528ae15e028a59b70f69b"
      name: "{{ item.name }}"
      site: "{{ item.site }}"
      status: active
      state: present
    loop:
      - name: Rack01
        site: Boston
      - name: Rack02
        site: Boston
      - name: Rack03
        site: Boston
      - name: Rack04
        site: Boston
    tags:
      - rack

  - name: "Add Device to nautobot"
    device:
      url: "http://10.92.59.139:8000"
      token: "47942ba1733978d2842528ae15e028a59b70f69b"
      name: "{{ item.name }}"
      rack: "{{ item.rack }}"
      site: "{{ item.site }}"
      device_role: "{{ item.device_role }}"
      device_type: "{{ item.device_type }}"
      status: active
      state: present
    loop:
      - name: cleaf01
        rack: "Rack01"
        site: "Boston"
        device_role: "cleaf"
        device_type: "7050X3"
      - name: cleaf02
        rack: "Rack01"
        site: "Boston"
        device_role: "cleaf"
        device_type: "7050X3"
      - name: cleaf03
        rack: "Rack02"
        site: "Boston"
        device_role: "cleaf"
        device_type: "7050X3"
      - name: cleaf04
        rack: "Rack02"
        site: "Boston"
        device_role: "cleaf"
        device_type: "7050X3"
      - name: bleaf01
        rack: "Rack03"
        site: "Boston"
        device_role: "bleaf"
        device_type: "7280R3"
      - name: bleaf02
        rack: "Rack03"
        site: "Boston"
        device_role: "bleaf"
        device_type: "7280R3"
      - name: spine01
        rack: "Rack03"
        site: "Boston"
        device_role: "spine"
        device_type: "7060X4"
      - name: spine02
        rack: "Rack03"
        site: "Boston"
        device_role: "spine"
        device_type: "7060X4"
      - name: mleaf01
        rack: "Rack01"
        site: "Boston"
        device_role: "mleaf"
        device_type: "720XP"
    tags:
      - device


