---
#############################################################
# Create VRFs in Nautobot
#############################################################    
# - name: Create VRFs within Nautobot
#   networktocode.nautobot.vrf:
#     url: "{{ nb_url }}"
#     token: "{{ nb_token }}"
#     validate_certs: no
#     name: "{{ item.name }}"
#     description: "{{ item.description }}"
#     state: present
#   loop: "{{ vrf }}"

- name: Create VRFs within Nautobot
  networktocode.nautobot.vrf:
    url: "{{ nb_url }}"
    token: "{{ nb_token }}"
    validate_certs: no
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    tenant: "{{ item.tenant|default(omit) }}"
    enforce_unique: "{{ item.enforce_unique|default(false) }}"
    state: present
  loop: "{{ vrf }}"
  tags:
    - vrf

#############################################################
# Create prefixes for each VRF in Nautobot
#############################################################
# - name: Create prefixes and assign to VRFs within Nautobot
#   networktocode.nautobot.prefix:
#     url: "{{ nb_url }}"
#     token: "{{ nb_token }}"
#     validate_certs: no
#     family: 4
#     prefix: "{{ item.prefix }}"
#     description: "{{ item.description }}"
#     vrf: "{{ item.name }}"
#     status: active
#     state: present  
#   loop: "{{ vrf }}"

- name: Create prefixes and assign to VRFs within Nautobot
  networktocode.nautobot.prefix:
    url: "{{ nb_url }}"
    token: "{{ nb_token }}"
    validate_certs: no
    family: 4
    prefix: "{{ item.prefix }}"
    description: "{{ item.description }}"
    vrf: "{{ item.name }}"
    tenant: "{{ item.tenant|default(omit) }}"
    is_pool: true
    status: active
    state: present  
  loop: "{{ vrf }}"
  tags:
    - vrf
