---
#############################################################
# Create Site in Nautobot
#############################################################  
- name: Create site with all parameters
  networktocode.nautobot.site:
    url: "{{ nb_url }}"
    token: "{{ nb_token }}"
    validate_certs: no
    name: "{{ item.name }}"
    status: "{{ item.status }}"
    asn: "{{ item.asn |default(omit) }}"
    time_zone: "{{ item.time_zone |default(omit) }}"
    description: "{{ item.description |default(omit) }}"
    physical_address: "{{ item.physical_address |default(omit) }}"
    shipping_address: "{{ item.shipping_address |default(omit) }}"
    latitude: "{{ item.latitude |default(omit) }}"
    longitude: "{{ item.longitude |default(omit) }}"
    contact_name: "{{ item.contact_name |default(omit) }}"
    contact_phone: "{{ item.contact_phone |default(omit) }}"
    contact_email: "{{ item.contact_email |default(omit) }}"
    region: "{{ item.region |default(omit) }}"
    slug: "{{ item.slug |default(omit) }}"
    comments: "{{ item.comments |default(omit) }}"
    state: present
  loop: "{{ sites }}"
  tags:
    - site
