---
#############################################################
# Create Site in Nautobot
#############################################################  
- name: Create site with all parameters
  networktocode.nautobot.site:
    url: "{{ nb_url }}"
    token: "{{ nb_token }}"
    validate_certs: no
    name: "{{ item.name }}"
    status: "{{ item.status }}"
    asn: "{{ item.asn if item.asn else omit }}"
    time_zone: "{{ item.time_zone if item.time_zone else omit }}"
    description: "{{ item.description if item.description else omit }}"
    physical_address: "{{ item.description if item.description else omit }}"
    shipping_address: "{{ item.shipping_address if item.shipping_address else omit }}"
    latitude: "{{ item.latitude if item.latitude else omit }}"
    longitude: "{{ item.longitude if item.longitude else omit }}"
    contact_name: "{{ item.contact_name if item.contact_name else omit }}"
    contact_phone: "{{ item.contact_phone if item.contact_phone else omit }}"
    contact_email: "{{ item.contact_email if item.contact_email else omit }}"
    region: "{{ item.region if item.region else omit }}"
    slug: "{{ item.slug if item.slug else omit }}"
    comments: "{{ item.comments if item.comments else omit }}"
    state: present
  loop: "{{ sites }}"
  tags:
    - site
