FROM ubuntu:latest
RUN apt update && apt install openssh-server sudo -y
# Create a user “sshuser” and group “lab”
RUN groupadd lab && useradd -ms /bin/bash -g lab lab && gpasswd -a lab sudo
# Create lab directory in home
RUN mkdir -p /home/lab/.ssh && mkdir -p /root/.ssh
# Copy the ssh public key in the authorized_keys file. The idkey.pub below is a public key file you get from ssh-keygen. They are under ~/.ssh directory by default.
COPY files/id_rsa.pub /home/lab/.ssh/authorized_keys
COPY files/id_rsa.pub /root/.ssh/authorized_keys
# change ownership of the key file. 
RUN chown lab:lab /home/lab/.ssh/authorized_keys && chmod 600 /home/lab/.ssh/authorized_keys
# Start services: ssh/lldpd
RUN service ssh start
# Expose docker port 22
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]
