---
#############################################################
# Create Devices in Nautobot
#############################################################
- name: Building Node Design Yaml to load nautobot
  template: 
    src: "node_design_load.j2"
    dest: "inventory/nautobot_vars/_nodes_design.yaml"
  tags:
    - build_node